apiVersion: 1

policies:
  - orgId: 1
    receiver: USSD email alerts
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: USSD email alerts
        object_matchers:
          - [service, =, ussd-engine]
